[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"

[lib]
name = "d01"
path = "src/shared.rs"
doctest = false

[[bin]]
name = "p1"
path = "src/p1.rs"

[[bin]]
name = "p2"
path = "src/p2.rs"

[dependencies]
winnow = { workspace = true }
itertools = { workspace = true }
